# Generated by Django 5.2.1 on 2025-05-30 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordenes', '0001_initial'),
        ('productos', '0001_initial'),
        ('remitos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destino', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.destino')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remitos.remito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistica.destino')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.equipo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.pallet')),
            ],
        ),
    ]
