# Generated by Django 5.2.1 on 2025-05-30 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('depositos', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_remito', models.CharField(max_length=20)),
                ('numero_viaje', models.IntegerField()),
                ('detalle_transporte', models.CharField(max_length=30)),
                ('fecha_ingreso', models.DateTimeField()),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='depositos.deposito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RemitoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remito_despacho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='remitos.remito')),
            ],
        ),
        migrations.CreateModel(
            name='RemitoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('actualizado', models.DateTimeField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remitos.remito')),
            ],
        ),
    ]
